apiVersion: v1
kind: Secret
metadata:
  name: storage-secret
type: Opaque
data:
  access-key: "WUNBSkU0V05qWFIta1pfVU5pZWkzRnVZLQ=="
  secret-key: "WUNNNWFwWHJmenc0MnFWelNreGYzN0lCcHlIeU5sVnYyd0haMm15Tg=="